<?php

namespace S7tH\SpecimenBundle\Repository;

/**
 * TricksspecimenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TricksspecimenRepository extends \Doctrine\ORM\EntityRepository
{
}
