s7t_h_directory:
    resource: "@S7tHDirectoryBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults: { _controller: S7tHUserBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout