# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        S7tH\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        # user provider for my firewall
        # below a provider memory to declare my users directly on this file 
        #in_memory:
            #memory: 
                #users:
                    #admin: { password: adminpass, roles: ['ROLE_ADMIN'] }
        
        # below the provider to use our users from an entity and a data base
        main: #name of my provider
            entity: #my provider type, just below it's my entity user
                class: S7tH\UserBundle\Entity\User
                property: username # my entity var which serves of login

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # my main firewall
        main:
            pattern: ^/
            anonymous: true
            provider: main #we indicate to the firewall that we use this provider
            # activate a form to authenticate
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
