s7t_h_directory_tricklist:
    path:     /
    defaults: { _controller: S7tHDirectoryBundle:Tricks:index }

s7t_h_directory_trickadd:
    path:     /trick-add
    defaults: { _controller: S7tHDirectoryBundle:Tricks:add }

s7t_h_directory_trickedit:
    path:     /trick-edit/{id}
    defaults: { _controller: S7tHDirectoryBundle:Tricks:edit }

s7t_h_directory_trickdelete:
    path:     /trick-delete/{id}/{state}
    defaults: { _controller: S7tHDirectoryBundle:Tricks:delete }
    requirements:
        state: confirm|delete

s7t_h_directory_trickview:
    path:     /trick-view/number-{id}/page-{page}
    defaults: { _controller: S7tHDirectoryBundle:Tricks:view }
    requirements:
      page: \d+

s7t_h_directory_admin:
    path:     /admin
    defaults: { _controller: S7tHDirectoryBundle:Admin:index }

s7t_h_directory_adminlist:
    path:     /admin-list-category
    defaults: { _controller: S7tHDirectoryBundle:Admin:list }

s7t_h_directory_adminadd:
    path:     /admin-add-category
    defaults: { _controller: S7tHDirectoryBundle:Admin:add }

s7t_h_directory_adminedit:
    path:     /admin-edit-category/{id}
    defaults: { _controller: S7tHDirectoryBundle:Admin:edit }

s7t_h_directory_admindelete:
    path:     /admin-delete-category/{id}
    defaults: { _controller: S7tHDirectoryBundle:Admin:delete }

s7t_h_directory_adminmember:
    path:     /admin-members
    defaults: { _controller: S7tHDirectoryBundle:Admin:member }

s7t_h_directory_adminmember_role:
    path:     /member-role/{nick}
    defaults: { _controller: S7tHDirectoryBundle:Admin:rolemember }
