<?php

namespace S7tH\DirectoryBundle\Repository;

/**
 * CommentaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($limit)
    {
        $qb = $this->createQueryBuilder('c');
        // On fait une jointure avec l'entité Advert avec pour alias « adv »
        $qb
          ->innerJoin('c.tricks', 'tks')
          ->addSelect('tks');

        // Puis on ne retourne que $limit résultats
        $qb->setMaxResults($limit);
        // Enfin, on retourne le résultat
        return $qb
          ->getQuery()
          ->getResult();
    }
}
